spring:
  datasource:
    url: jdbc:mysql://localhost:3306/mail_manage?userUnicode=true&characterEncoding=utf-8&serverTimezone=UTC
    username: root
    password: 123456
    type: com.alibaba.druid.pool.DruidDataSource
  thymeleaf:
    mode: HTML

mybatis:
  config-location: classpath:/mybatis-conf/mybatis-config.xml
  mapper-locations: classpath:mapper/*.xml

logging:
  level:
    root: info
    com.wzz: debug
  file: logs/MailManage-dev.log


